/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Answer { 'questionId' : bigint, 'choice' : bigint }
export interface LeaderboardEntry {
  'displayName' : string,
  'player' : Principal,
  'totalScore' : bigint,
}
export interface Level {
  'id' : bigint,
  'theme' : string,
  'name' : string,
  'questions' : Array<Question>,
}
export interface PlayerProgress {
  'lastPlayed' : Time,
  'streak' : bigint,
  'displayName' : string,
  'player' : Principal,
  'totalScore' : bigint,
  'currentLevel' : bigint,
}
export interface Question {
  'id' : bigint,
  'text' : string,
  'correctAnswer' : bigint,
  'options' : Array<string>,
}
export interface SubmissionResult {
  'streak' : bigint,
  'score' : bigint,
  'totalScore' : bigint,
  'newLevel' : bigint,
  'correctAnswers' : bigint,
  'passed' : boolean,
}
export type Time = bigint;
export interface _SERVICE {
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getLevel' : ActorMethod<[bigint], Level>,
  'getPlayerProgress' : ActorMethod<[Principal], PlayerProgress>,
  'resetLevel' : ActorMethod<[bigint], undefined>,
  'setDisplayName' : ActorMethod<[string], undefined>,
  'submitAnswers' : ActorMethod<[bigint, Array<Answer>], SubmissionResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];