/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LeaderboardEntry = IDL.Record({
  'displayName' : IDL.Text,
  'player' : IDL.Principal,
  'totalScore' : IDL.Nat,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Level = IDL.Record({
  'id' : IDL.Nat,
  'theme' : IDL.Text,
  'name' : IDL.Text,
  'questions' : IDL.Vec(Question),
});
export const Time = IDL.Int;
export const PlayerProgress = IDL.Record({
  'lastPlayed' : Time,
  'streak' : IDL.Nat,
  'displayName' : IDL.Text,
  'player' : IDL.Principal,
  'totalScore' : IDL.Nat,
  'currentLevel' : IDL.Nat,
});
export const Answer = IDL.Record({
  'questionId' : IDL.Nat,
  'choice' : IDL.Nat,
});
export const SubmissionResult = IDL.Record({
  'streak' : IDL.Nat,
  'score' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'newLevel' : IDL.Nat,
  'correctAnswers' : IDL.Nat,
  'passed' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getLevel' : IDL.Func([IDL.Nat], [Level], ['query']),
  'getPlayerProgress' : IDL.Func([IDL.Principal], [PlayerProgress], ['query']),
  'resetLevel' : IDL.Func([IDL.Nat], [], []),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
  'submitAnswers' : IDL.Func(
      [IDL.Nat, IDL.Vec(Answer)],
      [SubmissionResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LeaderboardEntry = IDL.Record({
    'displayName' : IDL.Text,
    'player' : IDL.Principal,
    'totalScore' : IDL.Nat,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Level = IDL.Record({
    'id' : IDL.Nat,
    'theme' : IDL.Text,
    'name' : IDL.Text,
    'questions' : IDL.Vec(Question),
  });
  const Time = IDL.Int;
  const PlayerProgress = IDL.Record({
    'lastPlayed' : Time,
    'streak' : IDL.Nat,
    'displayName' : IDL.Text,
    'player' : IDL.Principal,
    'totalScore' : IDL.Nat,
    'currentLevel' : IDL.Nat,
  });
  const Answer = IDL.Record({ 'questionId' : IDL.Nat, 'choice' : IDL.Nat });
  const SubmissionResult = IDL.Record({
    'streak' : IDL.Nat,
    'score' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'newLevel' : IDL.Nat,
    'correctAnswers' : IDL.Nat,
    'passed' : IDL.Bool,
  });
  
  return IDL.Service({
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getLevel' : IDL.Func([IDL.Nat], [Level], ['query']),
    'getPlayerProgress' : IDL.Func(
        [IDL.Principal],
        [PlayerProgress],
        ['query'],
      ),
    'resetLevel' : IDL.Func([IDL.Nat], [], []),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
    'submitAnswers' : IDL.Func(
        [IDL.Nat, IDL.Vec(Answer)],
        [SubmissionResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };